version: "3.8"

services:
  app:
    container_name: yabw-backend
    build: .
    command: uvicorn app.main:server --host 0.0.0.0 --port 8080 --reload
    ports:
      - "8080:8080"
    volumes:
      - ./app:/code/app
    depends_on:
      - postgres

  postgres:
    container_name: yabw-postgres
    image: "postgres:15-alpine"
    restart: unless-stopped
    environment:
      - POSTGRES_DB=you-are-being-watched
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init_db.sh://docker-entrypoint-initdb.d/init_db.sh

volumes:
  postgres_data: {}
